# Generated by Django 2.1 on 2018-08-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
