# Generated by Django 2.1 on 2018-08-19 09:59

from django.db import migrations
import reauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('reauth', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', reauth.models.UserManager()),
            ],
        ),
    ]
